### ISSUE TITLE
HTTPError 308: Permanent Redirect - plotsummary

### ISSUE THREAD

**Issue by m-hoseyny** [cinemagoer/cinemagoer#438]
I get an error in "plotsummary" section, Since Yesterday. This issue raises when using "get_movie" method to get movie/series information from IMDB.

*You can find the trace of the error here*

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.8/site-packages/imdb/__init__.py", line 423, in get_movie
    self.update(movie, info)
  File "/lib/python3.8/site-packages/imdb/__init__.py", line 831, in update
    ret = method(mopID)
  File "/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 485, in get_movie_plot
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')
  File "/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 379, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File "/lib/python3.8/site-packages/imdb/parser/http/__init__.py", line 249, in retrieve_unicode
    raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt13051810/plotsummary', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 308: 'Permanent Redirect'>}
```

#### Version of cinemagoer==2022.02.11, Python==3.8.6

I check the url and IMDB redirect the ```https://www.imdb.com/title/tt13051810/plotsummary``` to ```https://www.imdb.com/title/tt13051810/plotsummary/```. I think this raises the error in the program!

**Comment by bluboyo** [comment]
Same for me. Everything is broken.

**Comment by alberanid** [comment]
Please upgrade to the latest version from the repository and let us know if it still happens.

**Comment by m-hoseyny** [comment]
Thank you for your response.
It was solved when I upgrade to the latest version.

Sorry for dummy issue :))

**Comment by bluboyo** [comment]
I still get an error, not the same though. Maybe i should make a new issue? Worked fine a few months ago

Traceback (most recent call last):
    File "/home/user/.local/lib/python3.10/site-packages/imdb/utils.py", line 1503, in __getitem__
    rawData = self.data[key]
KeyError: 'Arithmetic mean'

**Comment by angry-elf** [comment]
main branch works in python3, but not in 2.7:


```

>>> entry = ia.get_movie('0133093')


2023-02-05 09:44:15,085 CRITICAL [imdbpy] .../venv/lib64/python2.7/site-packages/imdb/__init__.py:853: caught an exception retrieving or parsing "plot" info set for mopID "0133093" (accessSystem: http)
Traceback (most recent call last):
  File ".../venv/lib64/python2.7/site-packages/imdb/__init__.py", line 848, in update
    ret = method(mopID)
  File ".../venv/lib64/python2.7/site-packages/imdb/parser/http/__init__.py", line 499, in get_movie_plot
    cont = self._retrieve(self.urls['movie_main'] % movieID + 'plotsummary')
  File ".../venv/lib64/python2.7/site-packages/imdb/parser/http/__init__.py", line 393, in _retrieve
    ret = self.urlOpener.retrieve_unicode(url, size=size)
  File ".../venv/lib64/python2.7/site-packages/imdb/parser/http/__init__.py", line 234, in retrieve_unicode
    response = uopener.open(url)
  File "/usr/lib64/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib64/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib64/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File ".../venv/lib64/python2.7/site-packages/imdb/parser/http/__init__.py", line 160, in http_error_308
    return super(IMDbHTTPRedirectHandler, self).http_error_302(req, fp, code, msg, headers)
TypeError: super() argument 1 must be type, not classobj


```

**Comment by alberanid** [comment]
yes, please: both @bluboyo and @angry-elf issues seems to be unrelated to the one presented by @m-hoseyny ; please open a separated issue since I'm closing this one.
