### ISSUE TITLE
in series episodes doesn't work anymore.

### ISSUE THREAD

**Issue by Catpablo** [cinemagoer/cinemagoer#475]
when searching for series the ia.update(series,'episodes') function doesn't work. It was working 2 days ago. Did something happen on the server side?

#### Code:

f = ia.search_movie("friends")
f = f[0]
ia.update(f, "episodes")

e = f["number of episodes"]
print(e)

#### What's the expected result?
228
- 

#### What's the actual result?
0
-

**Comment by Catpablo** [comment]
`ia.update(series,'episodes')`

returns:


KeyError                                  Traceback (most recent call last)
[<ipython-input-14-36a15d9a1d9c>](https://localhost:8080/#) in <cell line: 1>()
----> 1 ia.update(series,'episodes')

1 frames
[/usr/local/lib/python3.10/dist-packages/imdb/parser/http/__init__.py](https://localhost:8080/#) in get_movie_episodes(self, movieID, season_nums)
    665             nr_eps += len(other_d['data']['episodes'].get(season) or [])
    666             if data_d:
--> 667                 data_d['data']['episodes'][season] = other_d['data']['episodes'][season]
    668             else:
    669                 data_d = other_d

KeyError: 3

**Comment by Greenleaf77** [comment]
Same issue :(

**Comment by dineshpinto** [comment]
had the same issue, looks like it may be bad data returned from the URL, seems to happen randomly

as a workaround, threw together a quick and dirty script to get the episode list for a single season 

YMMV

```python
from imdb import Cinemagoer, Movie

ia = Cinemagoer()

def get_season_episodes(id: str, season: int) -> list[Movie]:
    while True:
        try:
            cont = ia._retrieve(ia.urls['movie_main'] % f"{id}" + f'episodes?season={season}')
            other_d = ia.mProxy.season_episodes_parser.parse(cont)
            other_d = ia._purge_seasons_data(other_d)
            other_d['data'].setdefault('episodes', {})
            return list(other_d["data"]["episodes"][season].values())
        except KeyError:
            continue

episodes = get_season_episodes(id="1442437", season=1)
```

**Comment by Catpablo** [comment]
> had the same issue, looks like it may be bad data returned from the URL, seems to happen randomly
> 
> 
> 
> as a workaround, threw together a quick and dirty script to get the episode list for a single season 
> 
> 
> 
> YMMV
> 
> 
> 
> ```python
> 
> from imdb import Cinemagoer, Movie
> 
> 
> 
> ia = Cinemagoer()
> 
> 
> 
> def get_season_episodes(id: str, season: int) -> list[Movie]:
> 
>     while True:
> 
>         try:
> 
>             cont = ia._retrieve(ia.urls['movie_main'] % f"{id}" + f'episodes?season={season}')
> 
>             other_d = ia.mProxy.season_episodes_parser.parse(cont)
> 
>             other_d = ia._purge_seasons_data(other_d)
> 
>             other_d['data'].setdefault('episodes', {})
> 
>             return list(other_d["data"]["episodes"][season].values())
> 
>         except KeyError:
> 
>             continue
> 
> 
> 
> episodes = get_season_episodes(id="1442437", season=1)
> 
> ```

Though the same solution but for now getting episodes data from tmdbapi. Much easier.

**Comment by pkwagner** [comment]
Maybe try setting the Edge User Agent [here](https://github.com/cinemagoer/cinemagoer/blob/69770fd3a5d547d70ab4c6f99e8dc4c378bd18e1/imdb/parser/http/__init__.py#L175)?

I tested it out using my Safari User Agent (which displays the old view as well), but haven't succeeded so far.

**Comment by sandrotosi** [comment]
this is just a colossal hack, for now.

in `imdb/parser/http/__init__.py` i modified `get_movie_episodes()` to this:

```
    def get_movie_episodes(self, movieID, season_nums='all'):
        while True:
            cont = self._retrieve(self.urls['movie_main'] % movieID + 'episodes')
            temp_d = self.mProxy.season_episodes_parser.parse(cont)
            print(temp_d)
            if temp_d['data']:
                break
        if isinstance(season_nums, int):
            season_nums = {season_nums}
        elif (isinstance(season_nums, (list, tuple)) or
              not hasattr(season_nums, '__contains__')):
            season_nums = set(season_nums)
        if not temp_d and 'data' in temp_d:
            return {}

        _seasons = temp_d['data'].get('_seasons') or []

        nr_eps = 0
        data_d = dict()

        for season in _seasons:
            while True:
                print(f"fetching {season=} season")
                if season_nums != 'all' and season not in season_nums:
                    continue
                # Prevent Critical error if season is not found #330
                try:
                    cont = self._retrieve(
                        self.urls['movie_main'] % movieID + 'episodes?season=' + str(season)
                    )
                except:
                    pass
                other_d = self.mProxy.season_episodes_parser.parse(cont)
                other_d = self._purge_seasons_data(other_d)
                if not other_d['data']:
                    continue
                other_d['data'].setdefault('episodes', {})
                # Prevent Critical error if season is not found #330
                try:
                    if not (other_d and other_d['data'] and other_d['data']['episodes'][season]):
                        continue
                except:
                    continue
                nr_eps += len(other_d['data']['episodes'].get(season) or [])
                if data_d:
                    data_d['data']['episodes'][season] = other_d['data']['episodes'][season]
                else:
                    data_d = other_d
                break
        if not data_d:
            data_d['data'] = dict()
        data_d['data']['number of episodes'] = nr_eps
        if 'episodes' not in data_d['data']:
            raise IMDbParserError(f"no episodes data")
        if len(_seasons) != len(data_d['data']['episodes'].keys()):
            raise IMDbParserError(f"{len(_seasons)=} != {len(data_d['data']['episodes'].keys())=}")
        return data_d
```

(there are probably some debugging commands left), essentially try to fetch until we get the old page that the parses understands

i have saved a copy of the new and old pages, and i'll see if i can manage to adjust the parser, but at least now my code works

**Comment by pkwagner** [comment]
Works perfectly for me, thanks! Do you consider opening a PR for it?

**Comment by sandrotosi** [comment]
> Works perfectly for me, thanks! Do you consider opening a PR for it?

naah this is trash, the proper fix (worth of a PR) is to adjust the parsers to handle the new format as well as the old one

**Comment by pkwagner** [comment]
Oh, my bad, didn't look to the code too close yet and assumed it would contain a new parser. Anyways, thanks for the quick fix and let's hope IMDb paddles back to their old design 😄

**Comment by alberanid** [comment]
>  the proper fix (worth of a PR) is to adjust the parsers to handle the new format as well as the old one

Since IMDb is changing their layout so often I fear it's better to wait until they settle on just one.

**Comment by sandrotosi** [comment]
> Since IMDb is changing their layout so often I fear it's better to wait until they settle on just one.

from a user perspective, while we wait for them to settle Cinemagoer is essentially useless. For this reason i think we should find an approach that works while IMDb is adjusting its layout

i'm not familiar (yet?) with the codebase, but maybe one way would be to specify multiple `Rule`s in `DOMHTMLSeasonEpisodesParser`  for each items in the `rules` list.

something like from:

```
        Rule(
            key='series link',
            extractor=Path('//div[@class="parent"]//a/@href')
        ),
```

to

```
        Rule(
            key='series link',
            extractors=[
                Path('//div[@class="parent"]//a/@href'),
                Path('//div[@class="Something"]//a/@tag'),
            ]
        ),
```

where the first `Path` matching "something" is what's returned

that has some simple advantages like:

1. old and new layout can co-exist for as long as IMDb is testing them out
2. the point above allows Cinemagoer to be usable while the layouts are being tested
3. once IMDb switches 100% of the traffic to the new layout, there's no code change needed (except for cleaning up the old rules, but that could happen at any time): the new `Path` will match all the searches
4. the same approach can be applied for future transitions for each part of the website (this time is series and episodes, but maybe next time it'll be movies, characters, something else)

**Comment by uyar** [comment]
@sandrotosi That is doable and I can have a go at it in Piculet. The "cleaning up of old rules" is a bit tricky though. We need a way to keep track of which rules aren't needed anymore because having many useless rules could make the code harder to maintain. Actually, we have a similar problem in the current code base in the form of pre- and postprocessors; some of these are probably also obsolete. If possible, I would prefer to have a plan about this before proceeding.

**Comment by uyar** [comment]
As a side note, it's been a long time since I've checked the code, but it should be possible to have multiple rules using the same key. The difference with the proposed approach would be that the last match wins rather than the first one.

**Comment by sandrotosi** [comment]
> @sandrotosi That is doable and I can have a go at it in Piculet.

great!

> The "cleaning up of old rules" is a bit tricky though. We need a way to keep track of which rules aren't needed anymore because having many useless rules could make the code harder to maintain.

makes sense,

> Actually, we have a similar problem in the current code base in the form of pre- and postprocessors; some of these are probably also obsolete. If possible, I would prefer to have a plan about this before proceeding.

hm, im not sure we should delaying intruducing multi-rules (which enables users to actually take advantage of this library) until a valid/working deprecation & removal policy is found. currently there's a single rule per element, and with this change there will be 2 (old and new layout). once they are implemented, and used, it may also be more evident how to identify rules no longer matching anything (it could be a GH action, running a series of tests that returns which rules still matches something)

> As a side note, it's been a long time since I've checked the code, but it should be possible to have multiple rules using the same key.

that's great, how can i start playing with this? i had a quick look at one of the keys, `'_seasons'`, and now it's the value of a series of `li` elements with attribute `data-testid="tab-season-entry"` (yep, the `data-testid` name sounds suspicious)

> The difference with the proposed approach would be that the last match wins rather than the first one.

what you mean by win? i think that which ever rule matches something, it should be what we return.

Say we have `[Rule1, Rule2, Rule3]`, Rule1 and Rule3 match nothing while Rule2 matches, then we should return what Rule2 matched

**Comment by uyar** [comment]
> hm, im not sure we should delaying intruducing multi-rules (which enables users to actually take advantage of this library) until a valid/working deprecation & removal policy is found. currently there's a single rule per element, and with this change there will be 2 (old and new layout). once they are implemented, and used, it may also be more evident how to identify rules no longer matching anything (it could be a GH action, running a series of tests that returns which rules still matches something)
> 

I do have some ideas about tracking whether a rule matches anything or not during tests. One thing that I haven't figured out yet is how to cache the test pages; at the moment we assume that there is only one page.

> > As a side note, it's been a long time since I've checked the code, but it should be possible to have multiple rules using the same key.
> 
> that's great, how can i start playing with this? i had a quick look at one of the keys, `'_seasons'`, and now it's the value of a series of `li` elements with attribute `data-testid="tab-season-entry"` (yep, the `data-testid` name sounds suspicious)
> 

Add another rule (preferably below the existing one, in case both match) and use the same key.

> what you mean by win? i think that which ever rule matches something, it should be what we return.
> 

If only one rule matches, there shouldn't be a difference. If multiple rules match, the result of the last match will be stored. This shouldn't  be a problem in our typical use case.

**Comment by alberanid** [comment]
> Refreshing the page on Chrome always gives me the new layout, while on Edge I always get the old one

That's interesting.

I agree with @pkwagner : is it possible to force it to always use a single layout changing [the User-Agent header](https://github.com/cinemagoer/cinemagoer/blob/master/imdb/parser/http/__init__.py#L175)?

That would solve the need to have multiple rules... at least until they force the other layout to anyone.

**Comment by sandrotosi** [comment]
> > Refreshing the page on Chrome always gives me the new layout, while on Edge I always get the old one
> 
> That's interesting.
> 
> I agree with @pkwagner : is it possible to force it to always use a single layout changing [the User-Agent header](https://github.com/cinemagoer/cinemagoer/blob/master/imdb/parser/http/__init__.py#L175)?

i dont think it's a good heuristic: i updated UA to the one my browser uses, which appears to return more often the old layout when visiting the IMDb website, *BUT* using cinemagoer it does not make any difference (consider the vastly higher number of requests performed by this module vs the browser) and the old layout is returned along with the new one.

> That would solve the need to have multiple rules... at least until they force the other layout to anyone.

i think for the future-proof of this project, and given the recent frequent layout changes in IMDb a multi rules approach is the preferred solution. admittedly i didnt have time to look into this that much  (my brutal retry-until-i-get-the-old-layout workaround satisfied my immediate needs) and the new layout is a bit more complex HMTL-wise, so some work is needed here

**Comment by sandrotosi** [comment]
it appears IMDb is now routing 100% of the trafic to the new layout, so addressing this is becoming more urgent (and i still have not find the time to figure out the new regexes :( )

**Comment by uyar** [comment]
I've made an attempt at fixing this. Now most tests pass. For the "Friends" example it returns 234 instead of 228. I'm closing this now. Feel free to reopen it if doesn't work properly. If it works partially, a separate issue could be better.

**Comment by titojff** [comment]
It seems that now they stoped A/B testing are using the final version

**Comment by dwgb93** [comment]
Neither the Friends example above nor the unit tests produce the correct results.

The following is my minimal (non-)working example using cinemagoer-2023.9.23 containing @uyar 's fixes

    from imdb import Cinemagoer
    ia = Cinemagoer()
    show = ia.get_movie('0944947') #Game of Thrones
    ia.update(show, 'episodes')
    show['episodes']

Any chance this could get looked at again?

**Comment by Greenleaf77** [comment]
Same, with the fixes from this thread stopped working earlier this week.
Now it's juust endlessly fetching seasons.
`{'data': {'episodes': {1: {}}, '_seasons': [1, 2, 3, 4], '_current_season': 1}, 'titlesRefs': {}, 'namesRefs': {}}
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
fetching season=1 season
...`

**Comment by sandrotosi** [comment]
@uyar did you notice there's a JSON payload in the page source?

```
<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"contentData":{"parentDisplayText":"Breaking Bad","entityMetadata":{"id":"tt0903747","certificate":{"rating":"TV-MA"},"runtime":{"seconds":181800},
```
this is just the beginning of that tag for https://www.imdb.com/title/tt0903747/episodes/?season=1&ref_=tt_eps_sn_1

but it contains all the information we're trying to parse from HTML -- should we switch to parse that json instead? that sounds like it would simplify dramatically the parsing

**Comment by uyar** [comment]
@sandrotosi Yes, I am aware. I've mentioned it in discussion #477. Parsing the JSON would be much simpler but it requires changing the base parsers and we are hesitant to do that since we suspect that the data might not remain available. I've made a small experiment about this and unfortunately changing the base parser is not that trivial and will require at least a few days of work.

**Comment by sandrotosi** [comment]
yup understood; the only reason i brought it up is because i was trying to understand why the episodes page cannot be parsed properly anymore and i've spent a couple of unfruitful hours navigating a rather complex codebase (from a newbie POV) to identify all the pieces that collaboratively parses a page, and still have no clue what the problem is.

unless you know exactly where to look, the current code is rather opaque to new contributors

**Comment by uyar** [comment]
I''ve started working on a complete rewrite. I've posted about it in #477. But I have no idea when (or even if) it will become usable.

**Comment by sandrotosi** [comment]
gotcha, any chance you have time to look at why episodes parsing is broken atm, or at least show me how to properly debug issues like this?

**Comment by sandrotosi** [comment]
i got back a bit of functionality by replacing https://github.com/cinemagoer/cinemagoer/blob/master/imdb/parser/http/movieParser.py#L2159 with `key=Path('.//div[@class="ipc-title__text"]/text()'),`

**Comment by uyar** [comment]
I've fixed a problem related to the episode title markup change. Now the tests are passing except for the "unknown" season test.

I'm reopening this issue.

**Comment by uyar** [comment]
OK, I pushed a more thorough fix. The markup for that page is not very structured and requires a lot of dirty workarounds to get the data. Note that the vote count is approximate. To get the exact vote count (which should rarely be necessary, I guess) the JSON data must be parsed.

**Comment by ErikKalkoken** [comment]
Sadly, this issue still happens for me. Tried with two series IDs:
- 0108778 (Friends)
- 0407362 (Battlestar Galactica)

Anything I can do on my end?

**Comment by Greenleaf77** [comment]
Stopped working for me again :(
<details>
   <summary>Error text:</summary>

```
---------------------------------------------------------------------------
IMDbParserError                           Traceback (most recent call last)
Cell In[1], line 5
      3 code = "7203552"
      4 series = ia.get_movie(code)
----> 5 ia.update(series, 'episodes')
      6 seasons = series['episodes']
      7 i = 1

File ~\anaconda3\Lib\site-packages\imdb\__init__.py:848, in IMDbBase.update(self, mop, info, override)
    846     method = lambda *x: {}
    847 try:
--> 848     ret = method(mopID)
    849 except Exception:
    850     _imdb_logger.critical(
    851         'caught an exception retrieving or parsing "%s" info set'
    852         ' for mopID "%s" (accessSystem: %s)',
    853         i, mopID, mop.accessSystem, exc_info=True
    854     )

File ~\anaconda3\Lib\site-packages\imdb\parser\http\__init__.py:683, in IMDbHTTPAccessSystem.get_movie_episodes(self, movieID, season_nums)
    681 data_d['data']['number of episodes'] = nr_eps
    682 if 'episodes' not in data_d['data']:
--> 683     raise IMDbParserError(f"no episodes data")
    684 if len(_seasons) != len(data_d['data']['episodes'].keys()):
    685     raise IMDbParserError(f"{len(_seasons)=} != {len(data_d['data']['episodes'].keys())=}")

IMDbParserError: no episodes data
```

</details>

**Comment by sandrotosi** [comment]
yep, i had to make these changes to movieParser:

```
class DOMHTMLSeasonEpisodesParser(DOMParserBase):
...

        Rule(
            key='_seasons',
            extractor=Path(
                foreach='//a[@data-testid="tab-season-entry"]',  # morph @ 2024-01-23
                path='./text()'
            )
        ),
        Rule(
            key='_current_season',
            extractor=Path('//a[@data-testid="tab-season-entry"][contains(@class, "ipc-tab--active")]/text()')  # morph @ 2024-01-23
        ),
``

**Comment by sandrotosi** [comment]
btw i lost 3 hours to find the right fix, i wish there'd be a much better way to do this, or at least to debug it

**Comment by uyar** [comment]
The code base is over over a decade old and it underwent significant changes. That makes it very difficult to refactor. In cinemagoerng, I have managed to set some infrastructure for parsing the much easier JSON payload. Hopefully I can backport it to cinemagoer at some point when the API is more stabilized.

**Comment by sandrotosi** [comment]
> The code base is over over a decade old and it underwent significant changes. That makes it very difficult to refactor. In cinemagoerng, I have managed to set some infrastructure for parsing the much easier JSON payload. Hopefully I can backport it to cinemagoer at some point when the API is more stabilized.

oh yeah parsing the JSON seems the right direction; i gave cinemagoerng a quick look and i didnt find a search function, so i cannot currently replace my use of cinemagoer but i'll look forward to the new project!

**Comment by Greenleaf77** [comment]
Seems like imdb changed layout/classes again. Ratings for the episodes stopped parsing. I changed this part to make it work again (movieParser.py file):

```
Rule(
            key='episodes',
            extractor=Rules(
                foreach='//h4',
                rules=[
                    Rule(
                        key=Path('.//a//text()'),
                        extractor=Rules(
                            rules=[
		                        Rule(
		                            key='link',
		                            extractor=Path('.//a/@href')
		                        ),
		                        Rule(
		                            key='original air date',
		                            extractor=Path('following-sibling::span/text()')
		                        ),
		                        Rule(
		                            key='rating',
		                            extractor=Path('../../..//span[contains(@class, "ipc-rating-star--rating")]/text()') # morph @ 2024-08-04
		                        ),
		                        Rule(
		                            key='votes',
		                            extractor=Path('../../..//span[contains(@class, "ipc-rating-star--voteCount")]/text()') # morph @ 2024-08-04
		                        ),
		                        Rule(
		                            key='plot',
		                            extractor=Path('../../..//div[@role="presentation"]//text()') # morph @ 2024-08-04
		                        )
		                    ]
                        )
                    )
                ]
            )
```

**Comment by filipopo** [comment]
Sadly I think it's broken again

**Comment by sandrotosi** [comment]
> Sadly I think it's broken again

I pushed my changes at https://github.com/sandrotosi/cinemagoer/tree/morph , it's based on an old HEAD but it works for episodes data with the current IMDb

**Comment by sandrotosi** [comment]
> If you can open a PR I'll merge it.

Im afraid i dont have the energy to rebase my changes to the latest `main`; my work is based out of an old branch which has diverged since

**Comment by alberanid** [comment]
This issue is no longer relevant due to issue #557: ss of June 2026, Cinemagoer no longer analyzes web pages and can only rely on non-commercial datasets.
